CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  carro VARCHAR(150) NOT NULL,
  marca VARCHAR(150) NOT NULL,
  cor VARCHAR(150) NOT NULL,
  ano VARCHAR(150) NOT NULL,
  estado VARCHAR(150) NOT NULL
);
